name: Publish gemfury Package

on: [push]

jobs:
  publish:
    if: startsWith(github.event.ref, 'refs/tags')
    
    name: Deploy Python package
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Debug version and tag
      run: |
        echo "GITHUB_REF=${GITHUB_REF}"
        echo "Extracted tag=${GITHUB_REF#refs/tags/}"
        grep "__version__" src/tpm2_pytss/internal/__init__.py
    
    - name: Check tag against package version
      run: |
        VERSION=$(grep -oE '__version__\s*=\s*"[^"]+"' src/tpm2_pytss/internal/__init__.py | cut -d '"' -f2)
        TAG_VERSION="${GITHUB_REF#refs/tags/}"
        echo "Extracted package version: $VERSION"
        echo "Tag version: $TAG_VERSION"
        if [ "$VERSION" != "$TAG_VERSION" ]; then
          echo "Error: Tag ($TAG_VERSION) does not match package version ($VERSION)"
          exit 1
        fi

    - name: Install Dependencies
      env:
        TPM2_TSS_VERSION: 3.0.0
      run: |
        python3 -m pip install --user --upgrade pip
        python3 -m pip install --user --upgrade setuptools twine wheel pkgconfig
        ./.ci/install-deps.sh

    - name: Test
      env:
        TEST: 1
      run: ./.ci/run.sh

    - name: Build distribution
      run: python setup.py sdist bdist_wheel

    - name: Publish artefacts
      run: twine upload dist/*
      env:
        TWINE_REPOSITORY_URL: https://pypi.fury.io/aruba-uxi/
        TWINE_USERNAME: ${{ secrets.FURY_AUTH }}
        TWINE_PASSWORD:
