name: Publish gemfury Package

on: [push]

jobs:
  publish:
    if: startsWith(github.event.ref, 'refs/tags')
    
    name: Deploy Python package
    runs-on: ubuntu-20.04
    container:
      image: debian:bookworm
      options: --security-opt seccomp=unconfined

    steps:
    - name: Install system dependencies
      run: |
        apt update
        apt install -y python3 python3-pip python3-venv python3-dev libssl-dev pkg-config

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Verify Python SSL Support
      run: python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"

    - name: Install Dependencies
      env:
        TPM2_TSS_VERSION: 3.0.0
      run: |
        python3 -m pip install --upgrade pip --break-system-packages
        python3 -m pip install --upgrade setuptools twine wheel pkgconfig --break-system-packages
        ./.ci/install-deps.sh

    - name: Test
      env:
        TEST: 1
      run: ./.ci/run.sh

    - name: Build distribution
      run: python3 setup.py sdist bdist_wheel

    - name: Publish artefacts
      run: twine upload dist/*
      env:
        TWINE_REPOSITORY_URL: https://pypi.fury.io/aruba-uxi/
        TWINE_USERNAME: ${{ secrets.FURY_AUTH_PUSH }}
        TWINE_PASSWORD:
